### ISSUE TITLE
Addon bei the Forge

### ISSUE THREAD

**Issue by Stonewall6165** [Plushtoast/dsa5-optolith#1]
Im Forge Store finde ich das Addon ist. Dazu kann ich beim Manifest Import eine Fehlermeldung:
Die Installation von Module ist fehlgeschlagen: Paket kann nicht von der URL heruntergeladen werden

**Comment by Plushtoast** [comment]
hoppla, sollte jetzt oder in wenigen minuten funktionieren

**Comment by Stonewall6165** [comment]
Geht, danke :)
